import { expect, test } from "@playwright/test";
import { enrollCalendarPlan, expectCanonicalTitle, expectRouteTitle, openRoute, usesMobileAppLayout, visibleNavLink } from "./helpers";

test.describe("core devotional journeys", () => {
  test("first-run setup reaches Scripture and returns with factual progress", async ({ page }) => {
    await enrollCalendarPlan(page); await page.locator(".today-plan-card summary").click(); const reading=page.locator(".reading-passage strong").first(); await expect(reading).toBeVisible(); const reference=(await reading.innerText()).trim(); await reading.click(); await expectCanonicalTitle(page, "Bible"); await expect(page.getByText(reference,{exact:true}).first()).toBeVisible(); const complete=page.getByRole("button",{name:"Mark reading complete"}); await expect(complete).toBeVisible(); await complete.click(); await page.getByRole("link",{name:"Back to Today"}).click(); await expect(page.getByText("1 of 4",{exact:true})).toBeVisible();
  });
  test("Scripture can become a reflection, prayer, and remembered history", async ({ page }) => {
    await openRoute(page,"/bible/JHN/3"); await expect(page.getByRole("heading",{level:2,name:"John 3"})).toBeVisible(); await page.getByRole("button",{name:"Select John 3:16"}).click(); await expect(page.getByRole("region",{name:"Actions for John 3:16"})).toBeVisible(); await page.getByRole("button",{name:/Reflect/}).click(); await expectRouteTitle(page, "Reflect", "Reflection"); const reflection=page.getByLabel("Daily reflection"); await reflection.fill("God's love in John 3:16 should shape the way I pray for people today."); await page.getByRole("button",{name:"Save reflection"}).click(); await expect(page.getByText(/Reflection (created and )?saved locally\./)).toBeVisible(); await page.getByRole("link",{name:/Create prayer/}).click(); await expectRouteTitle(page, "Add prayer"); await page.getByLabel("What do you want to pray about?").fill("Pray that I would love people sacrificially today."); await page.getByRole("button",{name:"Save prayer"}).click(); await expectRouteTitle(page, "Prayer"); await page.getByRole("button",{name:"Prayed now"}).click(); await expect(page.getByText("Prayed now recorded.")).toBeVisible(); if (usesMobileAppLayout(page)) { await page.getByRole("button",{name:"Back",exact:true}).click(); await expectRouteTitle(page, "Reflect", "Reflection"); await page.getByRole("button",{name:"Back",exact:true}).click(); await expectCanonicalTitle(page, "Today"); } await visibleNavLink(page,"History").click(); await expectCanonicalTitle(page, "History"); const today=page.locator(".history-day[href]").first(); await expect(today).toBeVisible(); await today.click(); const entries=page.locator(".history-entry"); await expect(entries.first()).toBeVisible(); expect(await entries.count()).toBeGreaterThanOrEqual(2); await expect(page.getByText(/John 3:16/).first()).toBeVisible();
  });
  test("Scripture search and collections stay understandable without leaving the Bible domain", async ({ page }) => {
    await openRoute(page,"/bible/JHN/3"); await page.getByRole("button",{name:"Select John 3:16"}).click(); await page.getByRole("button",{name:"More"}).click(); await page.getByRole("button",{name:"Add to collection"}).click(); await expectRouteTitle(page, "Collections", "Scripture collections"); await page.getByLabel("New collection").fill("Promises"); await page.getByRole("button",{name:"Add",exact:true}).click(); await page.locator(".collection-add-here").visible().click(); await expect(page.getByText("Passage added to collection.")).toBeVisible(); await expect(page.getByRole("link",{name:"John 3:16"})).toBeVisible(); await openRoute(page,"/search"); await page.getByLabel("Search MDD").fill("John 3:16"); await page.getByRole("button",{name:"Search",exact:true}).click(); await expect(page.getByRole("heading",{name:"Scripture",level:2,exact:true})).toBeVisible(); await expect(page.getByText("John 3:16",{exact:true}).first()).toBeVisible();
  });
});
