import {expect,test} from "@playwright/test";
import {seedFocusedPrayer} from "./focused-prayer-fixture";
import {writingSnapshot,writingDomainSnapshot} from "./writing-fixture";
import {openRoute,expectNoAxeViolations} from "./helpers";
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date("2026-04-24T07:00:00+02:00"));await seedFocusedPrayer(page);});
test("session answer recovery retains its original item and date across midnight without reconciliation",async({page})=>{
 const before=await writingDomainSnapshot(page);await page.getByRole("button",{name:"Mark answered",exact:true}).click();await page.locator("#session-answer-note").fill("Keep this answer note for tomorrow.");await expect(page.locator(".draft-status")).toHaveText("Draft kept on this device");await page.reload();await page.clock.setFixedTime(new Date("2026-04-25T07:00:00+02:00"));
 await openRoute(page,"/recovery");await page.getByRole("link",{name:/Answer note/}).click();const link=page.getByRole("link",{name:"Review in Focused prayer",exact:true});await expect(link).toHaveAttribute("href",/session=00000000-0000-4000-8000-000000009001/);await link.click();await page.getByRole("button",{name:"Recover for review",exact:true}).click();
 await expect(page.locator("#session-answer-note")).toHaveValue("Keep this answer note for tomorrow.");await expect(page.locator(".session-date-notice")).toContainText("April 24, 2026");expect(await writingDomainSnapshot(page)).toEqual(before);
 await page.locator(".session-answer").getByRole("button",{name:"Mark answered",exact:true}).click();await expect(page.locator(".session-heading-top")).toContainText("Request 2 of 3");const rows=Object.fromEntries(await writingSnapshot(page) as any);expect(rows.prayerSessions).toHaveLength(1);expect(rows.prayerSessions[0].localDate).toBe("2026-04-24");expect(rows.prayerSessionItems[0].outcome).toBe("ANSWERED");expect(rows.prayerResolutions).toHaveLength(1);expect(rows.activityEvents.filter((event:any)=>event.type==="PRAYER_ANSWERED")).toHaveLength(1);expect(rows.activityEvents.filter((event:any)=>event.type==="PRAYER_PRAYED")).toHaveLength(0);await expectNoAxeViolations(page);
});
test("an empty answer editor creates no private record",async({page})=>{
 const before=await writingSnapshot(page);await page.getByRole("button",{name:"Mark answered",exact:true}).click();await page.locator(".session-answer").getByRole("button",{name:"Cancel editing",exact:true}).click();await page.getByRole("dialog").getByRole("button",{name:"Discard and continue",exact:true}).click();await expect(page.locator(".session-answer")).toHaveCount(0);expect(await writingSnapshot(page)).toEqual(before);
});
test("a draft for an unavailable request stays copyable without starting or reconciling a session",async({page})=>{
 await page.getByRole("button",{name:"Mark answered",exact:true}).click();await page.locator("#session-answer-note").fill("Keep my unfinished note.");await expect(page.locator(".draft-status")).toHaveText("Draft kept on this device");
 await page.evaluate(async()=>{const database=await new Promise<IDBDatabase>(resolve=>{const request=indexedDB.open("my-daily-devotion");request.onsuccess=()=>resolve(request.result);});await new Promise<void>(resolve=>{const tx=database.transaction("prayers","readwrite"),store=tx.objectStore("prayers"),request=store.get("00000000-0000-4000-8000-000000008001");request.onsuccess=()=>store.put({...request.result,status:"WAITING",revision:2});tx.oncomplete=()=>resolve();});database.close();});
 // Leave by restarting into Recovery, rather than making an explicit session
 // entry that is allowed to reconcile. The draft's recovery reader is readonly.
 await page.goto(page.url().split("#")[0]+"#/recovery");await page.getByRole("link",{name:/Answer note/}).click();await expect(page.getByRole("link",{name:"Review in Focused prayer",exact:true})).toHaveCount(0);await expect(page.getByText("Keep my unfinished note.",{exact:true})).toBeVisible();const before=await writingDomainSnapshot(page);await page.reload();await expect(page.getByText("Keep my unfinished note.",{exact:true})).toBeVisible();expect(await writingDomainSnapshot(page)).toEqual(before);
});
test("private checkpoint failure does not prevent one valid explicit session answer",async({page})=>{
 await page.getByRole("button",{name:"Mark answered",exact:true}).click();await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==="editorDraftContents")throw new DOMException("Draft storage unavailable","QuotaExceededError");return put.apply(this,args);};});await page.locator("#session-answer-note").fill("Provision and peace.");await expect(page.getByRole("alert")).toContainText("Draft could not be kept");await page.locator(".session-answer").getByRole("button",{name:"Mark answered",exact:true}).click();await expect(page.locator(".session-heading-top")).toContainText("Request 2 of 3");const rows=Object.fromEntries(await writingSnapshot(page) as any);expect(rows.prayerResolutions).toHaveLength(1);expect(rows.activityEvents.filter((event:any)=>event.type==="PRAYER_ANSWERED")).toHaveLength(1);await expect(page.locator(".journal-status")).toHaveText("Answer recorded.");
});
