import {expect,test} from '@playwright/test';
import {openRoute,expectNoAxeViolations} from './helpers';
import {writingSnapshot,writingDomainSnapshot} from './writing-fixture';
import {seedMetadata,editMetadata} from './metadata-fixture';
import {seedArchive} from './archive-fixture';
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date('2026-04-24T07:00:00+02:00'));});
for(const kind of ['person','category','collection'] as const)test(`${kind} creation survives restart and requires explicit recovery`,async({page})=>{
 const route=kind==='collection'?'/bible/collections':'/prayer/'+(kind==='person'?'people':'categories');await openRoute(page,route);const before=await writingDomainSnapshot(page);
 await page.getByRole('button',{name:'Add '+kind,exact:true}).click();const label=kind==='collection'?'New collection':'Name';await page.getByLabel(label,{exact:true}).fill('Kept '+kind);if(kind==='person')await page.getByLabel('Notes',{exact:false}).fill('Private unfinished notes.');await expect(page.locator('.draft-status')).toHaveText('Draft kept on this device');await page.reload();
 await openRoute(page,'/recovery');await page.getByRole('link',{name:new RegExp('New '+kind)}).click();await page.getByRole('link',{name:'Review in '+(kind==='person'?'People':kind==='category'?'Categories':'Collections'),exact:true}).click();
 await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator(kind==='collection'?'#collection-editor':'#metadata-name')).toHaveValue('');const snapshot=await writingSnapshot(page);await page.getByRole('button',{name:'Keep current editor',exact:true}).click();expect(await writingSnapshot(page)).toEqual(snapshot);
 await page.getByText('Kept drafts for this editor',{exact:true}).click();await page.getByRole('button',{name:/Review kept draft/}).click();await page.getByRole('button',{name:'Recover for review',exact:true}).click();await expect(page.getByLabel(label,{exact:true})).toHaveValue('Kept '+kind);expect(await writingDomainSnapshot(page)).toEqual(before);
 await page.getByRole('button',{name:kind==='collection'?'Save collection':'Save '+kind,exact:true}).click();const rows=Object.fromEntries(await writingSnapshot(page) as any);expect(rows[kind==='person'?'people':kind==='category'?'categories':'collections']).toHaveLength(1);expect(rows.activityEvents).toHaveLength(0);expect(rows.editorDraftContents).toHaveLength(0);await expectNoAxeViolations(page);
});
for(const kind of ['people','categories'] as const)test(`${kind} baseline is retained and changed records need explicit comparison`,async({page})=>{
 await seedMetadata(page,kind);await editMetadata(page,kind==='people'?'Anna Wilson':'Personal',kind==='people'?'person':'category');await page.getByLabel('Name',{exact:true}).fill('Kept changed name');await expect(page.locator('.draft-status')).toHaveText('Draft kept on this device');await page.reload();
 await page.evaluate(async kind=>{const database=await new Promise<IDBDatabase>(resolve=>{const r=indexedDB.open('my-daily-devotion');r.onsuccess=()=>resolve(r.result);});const tx=database.transaction(kind,'readwrite'),store=tx.objectStore(kind),request=store.get(kind==='people'?'00000000-0000-4000-8000-000000010000':'00000000-0000-4000-8000-000000011000');request.onsuccess=()=>store.put({...request.result,name:'Saved changed name',revision:2});await new Promise<void>(resolve=>{tx.oncomplete=()=>resolve();});database.close();},kind);
 const before=await writingDomainSnapshot(page);await openRoute(page,'/recovery');await page.getByRole('link',{name:new RegExp(kind==='people'?'Person details':'Category name')}).click();await page.getByRole('link',{name:'Review in '+(kind==='people'?'People':'Categories'),exact:true}).click();await page.getByRole('button',{name:'Recover for review',exact:true}).click();await expect(page.getByLabel('Name',{exact:true})).toHaveValue('Kept changed name');await expect(page.getByRole('button',{name:'Save changes',exact:true})).toBeDisabled();expect(await writingDomainSnapshot(page)).toEqual(before);await page.getByRole('button',{name:'Compare versions',exact:true}).click();await page.getByRole('button',{name:'Keep my changes for review',exact:true}).click();await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.locator('.directory-row-copy strong').filter({hasText:'Kept changed name'})).toBeVisible();const rows=Object.fromEntries(await writingSnapshot(page) as any);expect(rows[kind].find((row:any)=>row.name==='Kept changed name').revision).toBe(3);expect(rows.activityEvents).toHaveLength(0);
});
for(const mode of ['rename','note'] as const)test(`collection ${mode} recovers the original selected passage and return`,async({page})=>{
 await seedArchive(page);const route='/bible/collections?collection=00000000-0000-4000-8000-000000013000&item=00000000-0000-4000-8000-000000014024&shown=40&return=%2Fsearch%3Fq%3Dgrace';await openRoute(page,route);await (mode==='rename'?page.getByRole('button',{name:'Rename',exact:true}):page.locator('#collection-note-00000000-0000-4000-8000-000000014024')).click();const label=mode==='rename'?'Collection name':'Passage note';await page.getByLabel(label,{exact:true}).fill('Recovered collection writing');await expect(page.locator('.draft-status')).toHaveText('Draft kept on this device');const before=await writingDomainSnapshot(page);await page.reload();await openRoute(page,'/recovery');await page.getByRole('link',{name:new RegExp(mode==='rename'?'Collection name':'Collection note')}).click();await page.getByRole('link',{name:'Review in Collections',exact:true}).click();await page.getByRole('button',{name:'Recover for review',exact:true}).click();await expect(page.getByLabel(label,{exact:true})).toHaveValue('Recovered collection writing');expect(await writingDomainSnapshot(page)).toEqual(before);expect(new URLSearchParams(new URL(page.url()).hash.split('?')[1]).get('return')).toBe('/search?q=grace');await page.getByRole('button',{name:mode==='rename'?'Save name':'Save note',exact:true}).click();await expect(page.getByText('Recovered collection writing',{exact:true}).first()).toBeVisible();const rows=Object.fromEntries(await writingSnapshot(page) as any);expect(rows.activityEvents).toHaveLength(0);expect(rows.editorDraftContents).toHaveLength(0);
});
test('pristine editor controls and offers remain write-free',async({page})=>{for(const route of ['/prayer/people','/prayer/categories','/bible/collections']){await openRoute(page,route);const before=await writingSnapshot(page);await page.getByRole('button',{name:route.includes('people')?'Add person':route.includes('categories')?'Add category':'Add collection',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect(await writingSnapshot(page)).toEqual(before);}});
