import { expect,test } from '@playwright/test';
import { seedHistoryJournal,historySnapshot } from './history-fixture';
import { expectNoAxeViolations,expectNoHorizontalOverflow,openRoute } from './helpers';
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date('2026-04-24T07:00:00+02:00'));});
test('History filters, pagination and return URLs preserve context with zero browsing writes',async({page})=>{
  await seedHistoryJournal(page,{count:25,priorYear:true});const before=await historySnapshot(page);
  await page.getByRole('button',{name:'Show more',exact:true}).click();await expect(page.locator('.history-journal-row')).toHaveCount(15);
  const url=page.url();await page.locator('#history-row-history-reflection-event').click();await expect(page.locator('.history-day-entry.is-selected')).toBeFocused();
  await page.locator('.history-back').click();await expect(page).toHaveURL(url);await expect(page.locator('.history-journal-row')).toHaveCount(15);await expect(page.locator('#history-row-history-reflection-event')).toBeFocused();
  const totals=await page.locator('.history-journal-stats').textContent();await page.getByRole('navigation',{name:'History views'}).getByRole('link',{name:'Prayer',exact:true}).click();await expect(page.locator('.history-journal-row')).toHaveCount(2);await expect(page.locator('.history-journal-stats')).toHaveText(totals!);
  await page.getByLabel('History period').selectOption('2025');await expect(page.locator('.history-journal-row')).toHaveCount(1);await page.getByRole('link',{name:'Search history and Scripture'}).click();await expect(page).toHaveURL(/return=/);await page.goBack();await expect(page.getByLabel('History period')).toHaveValue('2025');
  expect(await historySnapshot(page)).toEqual(before);
});
test('Calendar browses stored dates with a narrow accessible day-list fallback',async({page})=>{
  await seedHistoryJournal(page,{priorYear:true});const before=await historySnapshot(page);await page.getByLabel('History period').selectOption('2025');await expect(page).toHaveURL(/period=2025/);await expect(page.locator('.history-journal-row')).toHaveCount(1);await page.getByRole('link',{name:'Browse dates',exact:true}).click();await expect(page.getByRole('heading',{name:'December 2025'})).toBeVisible();
  await page.setViewportSize({width:320,height:844});await expect(page.locator('.history-calendar-grid')).toBeHidden();await expect(page.locator('.history-calendar-day-list a')).toHaveCount(1);await page.locator('.history-calendar-day-list a').click();await expect(page.getByRole('heading',{level:1})).toContainText('2025');await page.locator('.history-back').click();await expect(page.getByLabel('Month',{exact:true})).toHaveValue('2025-12');
  await page.getByRole('button',{name:'This month',exact:true}).click();await expect(page.getByLabel('Month',{exact:true})).toHaveValue('2026-04');await page.setViewportSize({width:390,height:844});await expect(page.locator('.history-calendar-grid')).toBeVisible();await expect(page.locator('.history-day[href]')).toHaveCount(5);
  await page.getByLabel('Month',{exact:true}).fill('2024-02');await expect(page.locator('.history-month-grid')).toContainText('29');await expect(page.locator('.history-month-grid')).not.toContainText('30');await expectNoHorizontalOverflow(page);await page.locator('.history-back').click();await expect(page.getByLabel('History period')).toHaveValue('2025');await expect(page.locator('#history-browse-dates')).toBeFocused();expect(await historySnapshot(page)).toEqual(before);
});
test('Moments excludes ordinary requests and discovers more than 200 reflective entries',async({page})=>{
  await seedHistoryJournal(page,{count:230});const before=await historySnapshot(page);await page.getByRole('link',{name:'Moments',exact:true}).click();await expect(page.locator('.history-journal-row')).toHaveCount(20);await expect(page.locator('.history-journal-list')).not.toContainText('Added a prayer request');
  for(let i=0;i<10;i++){await page.getByRole('button',{name:'Show more',exact:true}).click();await expect(page.locator('.history-journal-row')).toHaveCount(40+i*20);}await expect(page.locator('.history-journal-row')).toHaveCount(220);await expect(page.getByRole('status')).toContainText('220 of 227');
  await page.reload();await expect(page.locator('.history-journal-row')).toHaveCount(220);expect(await historySnapshot(page)).toEqual(before);
});
test('History retains mobile artwork, 44px controls and enlarged-text reflow',async({page})=>{
  await seedHistoryJournal(page);
  for(const width of [320,360,390,430,768,1440]){await page.setViewportSize({width,height:844});await expectNoHorizontalOverflow(page);await expect(page.locator('.history-reflection-band img')).toBeVisible();const heights=await page.locator('.history-search,.history-journal-tabs a,.history-period select,.history-activity-heading a').evaluateAll(items=>items.map(i=>i.getBoundingClientRect().height));heights.forEach(h=>expect(h).toBeGreaterThanOrEqual(43.999));}
  await page.setViewportSize({width:390,height:844});expect((await page.locator('.history-reflection-band').boundingBox())!.y).toBeLessThan(710);await expectNoAxeViolations(page);
  await page.setViewportSize({width:320,height:844});await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});await expectNoHorizontalOverflow(page);await expectNoAxeViolations(page);
  await page.getByRole('link',{name:'Browse dates',exact:true}).click();await expect(page.locator('.history-calendar-grid')).toBeHidden();await expectNoHorizontalOverflow(page);await expectNoAxeViolations(page);
});
test('Dark History and selected Day keep readable contrast and full writing',async({page})=>{
  await page.emulateMedia({colorScheme:'dark'});await seedHistoryJournal(page,{long:true});await expectNoAxeViolations(page);await page.locator('#history-row-history-reflection-event').click();await expect(page.locator('.history-entry-text')).toContainText('gentleness');await expect(page.getByRole('button',{name:'Show less'})).toBeVisible();await expectNoAxeViolations(page);await page.setViewportSize({width:320,height:844});await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});await expectNoHorizontalOverflow(page);
});
test('History quotes bundled BSB and keeps records when the optional quotation fails',async({page})=>{
  await seedHistoryJournal(page);const text=await page.locator('.history-reflection-band blockquote').innerText();expect(text).toContain('Because of the loving devotion of the LORD');expect(text).toContain('great is Your faithfulness');
  await page.route('**/bible/books/LAM.json',route=>route.abort());await page.reload();await expect(page.locator('.history-journal-row')).toHaveCount(5);await expect(page.locator('.history-reflection-band img')).toBeVisible();await expect(page.locator('.history-reflection-band blockquote')).toHaveCount(0);await expect(page.getByText('A quiet place to remember His faithfulness.',{exact:true})).toBeVisible();
});
test('History library errors are retryable and do not initialize or change records',async({page})=>{
  await seedHistoryJournal(page);const before=await historySnapshot(page);await page.evaluate(()=>{const original=IDBObjectStore.prototype.getAll;(window as any).restoreHistoryRead=()=>{IDBObjectStore.prototype.getAll=original;};IDBObjectStore.prototype.getAll=function(...args){if(this.name==='activityEvents')throw new DOMException('Synthetic read failure','UnknownError');return original.apply(this,args);};window.dispatchEvent(new Event('focus'));});
  await expect(page.getByRole('alert')).toBeVisible();await expect(page.locator('.history-journal-row')).toHaveCount(5);await page.evaluate(()=>(window as any).restoreHistoryRead());await page.getByRole('button',{name:'Try again'}).click();await expect(page.getByRole('alert')).toHaveCount(0);expect(await historySnapshot(page)).toEqual(before);
});
test('A source edit in another tab refreshes History without creating activity',async({page,context})=>{
  await seedHistoryJournal(page);const other=await context.newPage();await openRoute(other,'/today/reflection/2026-04-22');await other.getByLabel('Daily reflection').fill('Updated in another tab.');await other.getByRole('button',{name:'Save reflection',exact:true}).click();await expect(other.getByText(/saved locally/)).toBeVisible();await expect(page.locator('#history-row-history-reflection-event')).toContainText('Updated in another tab.');await expect(page.locator('.history-journal-stats')).toContainText('1');await other.close();
});
test('This year rolls forward while an explicit past year remains selected',async({page})=>{
  await seedHistoryJournal(page);const before=await historySnapshot(page);await page.clock.setFixedTime(new Date('2027-01-01T00:01:00+01:00'));await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByLabel('History period')).toContainText('This year · 2027');await expect(page.locator('.history-journal-row')).toHaveCount(0);await page.getByLabel('History period').selectOption('2026');await expect(page.locator('.history-journal-row')).toHaveCount(5);expect(await historySnapshot(page)).toEqual(before);
});
test('Invalid URL values recover and selected entry survives source return',async({page})=>{
  await seedHistoryJournal(page);await openRoute(page,'/history?period=invalid&view=no&shown=-1');await expect(page).toHaveURL(/period=this-year&view=overview&shown=5/);await page.locator('#history-row-history-reflection-event').click();const dayUrl=page.url();await page.getByRole('link',{name:'Open reflection',exact:true}).click();await expect(page.getByLabel('Daily reflection')).toBeVisible();if(await page.locator('.quiet-back-link').isVisible())await page.locator('.quiet-back-link').click();else await page.getByRole('button',{name:'Back',exact:true}).click();await expect(page).toHaveURL(dayUrl);await expect(page.locator('.history-day-entry.is-selected')).toBeFocused();await openRoute(page,'/history/day/2026-02-30');await expect(page.getByRole('heading',{name:'Invalid date'})).toBeVisible();
});
test('Reading handoff preserves M’Cheyne context and returns to the selected History entry',async({page})=>{
  await seedHistoryJournal(page);await page.locator('#history-row-history-reading').click();await expect(page.locator('.history-day-entry.is-selected')).toBeFocused();const dayUrl=page.url();await page.getByRole('link',{name:'Read passage',exact:true}).click();await expect(page.locator('.plan-reading-context')).toContainText('Day 114');await expect(page).toHaveURL(/enrollment=history-plan/);await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page).toHaveURL(/bible\/NUM\/2.*return=/);await page.getByRole('link',{name:'Return to devotional context',exact:true}).click();await expect(page).toHaveURL(dayUrl);await expect(page.locator('.history-day-entry.is-selected')).toBeFocused();
});
test('Grouped prayed actions open their individual records without recording another prayer',async({page})=>{
  await seedHistoryJournal(page);await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>(resolve=>{const r=indexedDB.open('my-daily-devotion');r.onsuccess=()=>resolve(r.result);});const tx=db.transaction('activityEvents','readwrite');for(let i=0;i<2;i++)tx.objectStore('activityEvents').put({id:`prayed-${i}`,type:'PRAYER_PRAYED',localDate:'2026-04-24',occurredAt:`2026-04-24T07:0${i}:00.000Z`,timeZone:'Europe/Berlin',subjectType:'prayer',subjectId:'history-prayer-0',metadata:{}});await new Promise<void>(resolve=>{tx.oncomplete=()=>resolve();});db.close();});await page.reload();await expect(page.getByText('Recorded 2 prayed actions',{exact:true})).toBeVisible();const before=await historySnapshot(page);await page.getByRole('link').filter({hasText:'Recorded 2 prayed actions'}).click();await expect(page.locator('.history-prayed-details')).toHaveAttribute('open','');await expect(page.locator('.history-prayed-details .history-day-entry')).toHaveCount(2);await expect(page.locator('.history-day-entry.is-selected')).toBeFocused();expect(await historySnapshot(page)).toEqual(before);
});
test('All secondary History views retain keyboard access and reflow at each required width',async({page})=>{
  await seedHistoryJournal(page);
  for(const route of ['/history/calendar?month=2026-04','/history/moments','/history/day/2026-04-22?entry=history-reflection-event']){
    await openRoute(page,route);await expect(page.getByRole('status').filter({hasText:/Opening/})).toHaveCount(0);
    for(const width of [320,360,390,430,768,1440]){await page.setViewportSize({width,height:844});await expectNoHorizontalOverflow(page);}
    await page.setViewportSize({width:390,height:844});await page.locator('.history-back').focus();await expect(page.locator('.history-back')).toBeFocused();await page.locator('.history-search').focus();await expect(page.locator('.history-search')).toBeFocused();await expectNoAxeViolations(page);await page.keyboard.press('Enter');await expect(page).toHaveURL(/search\?return=/);await page.goBack();await expect(page.locator('.history-search')).toBeVisible();
  }
});
