import {expect,test} from '@playwright/test';
import {openRoute,expectNoAxeViolations,expectNoHorizontalOverflow} from './helpers';
import {dataSnapshot} from './data-fixture';
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date('2026-04-24T07:00:00+02:00'));await page.emulateMedia({reducedMotion:'reduce'});});
test('the introduction is optional and only explicit preferences are saved',async({page})=>{
 await openRoute(page,'/welcome');await expect(page.getByRole('heading',{name:'A gentle beginning'})).toBeVisible();const before=await dataSnapshot(page);await page.getByLabel('Preferred name (optional)').fill('Anna');expect(await dataSnapshot(page)).toEqual(before);await page.getByRole('button',{name:'Save greeting'}).click();await expect(page.getByRole('status')).toContainText('Greeting saved locally');await page.getByRole('button',{name:'Skip introduction'}).click();await expect(page.getByRole('heading',{name:'Good morning, Anna.'})).toBeVisible();await page.clock.setFixedTime(new Date('2026-04-24T14:00:00+02:00'));await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.getByRole('heading',{name:'Good afternoon, Anna.'})).toBeVisible();const after=await dataSnapshot(page);expect(after.planEnrollments).toHaveLength(0);expect(after.activityEvents).toHaveLength(0);
});
test('unenrolled readers see explanations and can use Scripture and Prayer freely',async({page})=>{
 await openRoute(page,'/today/plan?return=%2Fwelcome');await expect(page.getByText('Move forward after explicitly completing all four readings, with no deadline.')).toBeVisible();const before=await dataSnapshot(page);await page.getByRole('link',{name:'Explore the Bible'}).click();await expect(page.locator('.scripture-copy')).toBeVisible();await openRoute(page,'/prayer');await expect(page.getByRole('heading',{name:'Prayer',exact:true})).toBeVisible();const after=await dataSnapshot(page);expect(after.planEnrollments).toEqual(before.planEnrollments);expect(after.activityEvents).toEqual(before.activityEvents);
});
test('calendar completion returns to the revealed month with one explicit event',async({page})=>{
 await openRoute(page,'/today/plan');await page.getByRole('button',{name:'Follow today’s calendar'}).click();await expect(page.locator('.plan-current')).toContainText('Day 114');await page.getByLabel('Choose month').selectOption('3');const url=page.url(),before=await dataSnapshot(page);await page.locator('.plan-current .plan-journal-readings a').first().click();await expect(page.getByRole('button',{name:'Mark complete and continue'})).toBeVisible();await page.getByRole('button',{name:'Mark complete and continue'}).click();await expect(page).toHaveURL(url);await expect(page.getByLabel('Choose month')).toHaveValue('3');await expect(page.locator('.plan-current')).toContainText('Complete');const after=await dataSnapshot(page);expect((after.activityEvents as unknown[]).length).toBe((before.activityEvents as unknown[]).length+1);const browse=await dataSnapshot(page);await page.getByLabel('Choose month').selectOption('5');expect(await dataSnapshot(page)).toEqual(browse);
});
test('self-paced advances only after all four explicit completions',async({page})=>{
 await openRoute(page,'/today/plan');await page.getByRole('button',{name:'Start self-paced at Day 1'}).click();await expect(page.locator('.plan-current')).toContainText('Day 1');for(let index=0;index<4;index++){await page.locator('.plan-current .plan-journal-readings a').nth(index).click();await page.getByRole('button',{name:'Mark complete and continue'}).click();await expect(page.locator('.plan-current')).toContainText(index===3?'Day 2':'Day 1');}expect((await dataSnapshot(page)).activityEvents).toHaveLength(4);
});
test('invalid month normalizes and fallback enrollment browsing performs no repair writes',async({page})=>{
 await openRoute(page,'/today/plan');await page.getByRole('button',{name:'Start self-paced at Day 1'}).click();await expect(page.locator('.plan-current')).toContainText('Day 1');await page.evaluate(async()=>{const database=await new Promise<IDBDatabase>(resolve=>{const r=indexedDB.open('my-daily-devotion');r.onsuccess=()=>resolve(r.result);});const tx=database.transaction('preferences','readwrite');tx.objectStore('preferences').delete('mcheyne.activeEnrollmentId');await new Promise<void>(resolve=>tx.oncomplete=()=>resolve());database.close();});const before=await dataSnapshot(page);await openRoute(page,'/today/plan?month=99');await expect(page.locator('.plan-current')).toContainText('Day 1');await expect(page).not.toHaveURL(/month=/);expect(await dataSnapshot(page)).toEqual(before);
});
test('plan and introduction retain keyboard, contrast, targets and enlarged reflow',async({page})=>{
 test.setTimeout(120000);for(const theme of ['light','dark'] as const){await page.emulateMedia({colorScheme:theme});for(const route of ['/today/plan','/welcome']){await page.setViewportSize({width:320,height:844});await openRoute(page,route);await expect(page.locator('.plan-journal h1')).toBeVisible();const title=await page.locator('.plan-journal h1').boundingBox(),ornament=await page.locator('.journal-heading .grace-art').boundingBox();expect(ornament!.y+ornament!.height).toBeLessThanOrEqual(title!.y);await page.evaluate(()=>document.documentElement.style.fontSize='200%');await expectNoHorizontalOverflow(page);await expectNoAxeViolations(page);for(const button of await page.locator('.plan-journal button:visible').all())expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(44);await page.locator('.quiet-back-link').focus();await expect(page.locator('.quiet-back-link')).toBeFocused();await page.evaluate(()=>document.documentElement.style.fontSize='');}}
});

test('greeting settings return to the complete Data context and Bible retains introduction context',async({page})=>{
 for(const route of ['/data','/data?section=appearance&return=%2Fprayer%3Fstatus%3DWAITING']){
  await openRoute(page,route);const originalUrl=page.url();if(route==='/data')await page.getByText('Appearance',{exact:true}).click();await page.getByRole('link',{name:'Personalize your greeting →'}).click();await expect(page.locator('.welcome-name')).toBeVisible();await page.locator('.quiet-back-link').click();await expect(page).toHaveURL(originalUrl);
 }
 const origin='/welcome?return=%2Ftoday';await openRoute(page,origin);await page.getByRole('link',{name:'Open Bible',exact:true}).click();await expect(page.locator('.scripture-copy')).toBeVisible();await page.locator('.bible-reader-header').getByRole('link',{name:'Return to devotional context'}).click();await expect(page).toHaveURL(/#\/welcome\?return=%2Ftoday$/);
});

test('importing known progress is explicit and creates no historical completion events',async({page})=>{
 await openRoute(page,'/today/plan');await page.getByText('Already following this year?',{exact:true}).click();await page.getByLabel('Completed through date').fill('2026-01-02');await page.getByRole('button',{name:'Import through this date',exact:true}).click();await expect(page.locator('.plan-current')).toContainText('Day 114');const saved=await dataSnapshot(page);expect(saved.planEnrollments).toHaveLength(1);expect(saved.readingProgress).toHaveLength(8);expect(saved.activityEvents).toHaveLength(0);
});

test('optional plan asset failure is retryable without creating an enrollment',async({page})=>{
 await page.route('**/plans/mcheyne-classic.v1.json',route=>route.abort());await openRoute(page,'/today/plan');await expect(page.getByRole('alert')).toBeVisible();const before=await dataSnapshot(page);await page.unroute('**/plans/mcheyne-classic.v1.json');await page.getByRole('button',{name:'Try again'}).click();await expect(page.locator('.plan-setup')).toBeVisible();expect(await dataSnapshot(page)).toEqual(before);
});

test('leap-day pause and New Year refresh preserve the calendar enrollment and stored history',async({page})=>{
 await page.clock.setFixedTime(new Date('2028-02-29T07:00:00+01:00'));await openRoute(page,'/today/plan');await page.getByRole('button',{name:'Follow today’s calendar'}).click();await expect(page.locator('.plan-current')).toContainText('A leap-day pause');const before=await dataSnapshot(page);await page.clock.setFixedTime(new Date('2028-03-01T07:00:00+01:00'));await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.locator('.plan-current')).toContainText('Day 60');expect(await dataSnapshot(page)).toEqual(before);await page.clock.setFixedTime(new Date('2029-01-01T07:00:00+01:00'));await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await expect(page.locator('.plan-setup')).toBeVisible();expect(await dataSnapshot(page)).toEqual(before);
});

test('a failed greeting save retains the name and retry writes no devotional records',async({page})=>{
 await openRoute(page,'/welcome');await expect(page.getByRole('button',{name:'Save greeting'})).toBeEnabled();const before=await dataSnapshot(page);await page.getByLabel('Preferred name (optional)').fill('Anna');await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<IDBObjectStore['put']>){if(this.name==='preferences'){IDBObjectStore.prototype.put=put;throw new DOMException('Storage is full. Try again.','QuotaExceededError');}return put.apply(this,args);};});await page.getByRole('button',{name:'Save greeting'}).click();await expect(page.getByRole('alert')).toContainText('Storage is full');await expect(page.getByLabel('Preferred name (optional)')).toHaveValue('Anna');expect(await dataSnapshot(page)).toEqual(before);await page.getByRole('button',{name:'Save greeting'}).click();await expect(page.getByRole('status')).toContainText('Greeting saved locally');const saved=await dataSnapshot(page);expect(saved.activityEvents).toEqual(before.activityEvents);expect(saved.planEnrollments).toEqual(before.planEnrollments);await page.getByRole('button',{name:'Save greeting'}).click();await expect(page.getByRole('status')).toContainText('Greeting saved locally');expect(await dataSnapshot(page)).toEqual(saved);
});
