import { useEffect, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { db } from "../data/database";
import { loadBibleManifest } from "../scripture/loader";
import { bibleSearchHref, searchBible, type BibleSearchResult } from "../scripture/search";
import type { BibleManifest } from "../scripture/types";
import { prayerReferenceLabel } from "../prayer/references";
import { searchPersonal, type PersonalSearchHit, type PersonalSearchResults } from "./personal";

const emptyPersonal: PersonalSearchResults = { prayers: [], reflections: [], people: [], saved: [] };

export function SearchScreen() {
  const [params,setParams]=useSearchParams(); const q=params.get("q")??""; const [draft,setDraft]=useState(q); const bookId=params.get("book")??""; const testament=params.get("testament")??""; const returnTo=params.get("return")??"";
  const setFilter=(name:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(name,value);else next.delete(name);setParams(next);};
  useEffect(()=>setDraft(q),[q]);
  const [manifest,setManifest]=useState<BibleManifest|null>(null); const [bible,setBible]=useState<BibleSearchResult[]>([]); const [personal,setPersonal]=useState<PersonalSearchResults>(emptyPersonal); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{void loadBibleManifest().then(setManifest).catch(()=>setError("Could not load Scripture search. Please try again."));},[]);
  useEffect(()=>{ if(!q.trim()){setBible([]);setPersonal(emptyPersonal);setLoading(false);return;} let cancelled=false; setLoading(true); setError(""); setBible([]);setPersonal(emptyPersonal); Promise.all([searchBible(q,{bookId:bookId||null,testament:(testament||null) as "OT"|"NT"|null,limit:30}),searchPersonal(db,q)]).then(([b,p])=>{if(!cancelled){setBible(b);setPersonal(p);}}).catch((reason:unknown)=>{if(!cancelled)setError(reason instanceof Error?reason.message:"Search failed.");}).finally(()=>{if(!cancelled)setLoading(false);}); return()=>{cancelled=true;};},[q,bookId,testament]);
  const submit=(event:FormEvent)=>{event.preventDefault(); const next=new URLSearchParams(); if(returnTo)next.set("return",returnTo); if(draft.trim())next.set("q",draft.trim()); if(bookId)next.set("book",bookId); if(testament)next.set("testament",testament); setParams(next);};
  const total=personal.prayers.length+personal.reflections.length+personal.people.length+personal.saved.length+bible.length;
  return <main className="visual-screen search-screen mg-secondary-screen mg-search-workspace"><header className="screen-heading compact-heading mg-secondary-header"><p className="eyebrow">Find</p><h1>Search</h1><p className="screen-intro">Search Scripture and your private devotional archive. Find a passage, prayer, reflection, or saved note.</p></header><form className="global-search-form" onSubmit={submit}><input value={draft} onChange={(e)=>setDraft(e.target.value)} placeholder='Search “faith comes by hearing”, John 3:16, prayers, reflections…' aria-label="Search MDD"/><button type="submit">Search</button><div className="search-filters"><label>Book<select value={bookId} onChange={(e)=>setFilter("book",e.target.value)}><option value="">All books</option>{manifest?.books.map((book)=><option key={book.id} value={book.id}>{book.name}</option>)}</select></label><label>Testament<select value={testament} onChange={(e)=>setFilter("testament",e.target.value)}><option value="">Both</option><option value="OT">Old Testament</option><option value="NT">New Testament</option></select></label></div></form>{loading?<p className="muted-copy mg-inline-state mg-loading-state">Searching local data…</p>:error?<p className="mg-inline-state mg-error-state" role="alert">{error}</p>:q&&total===0?<p className="search-empty mg-empty-state">No results for “{q}”.</p>:null}{q&&!loading&&!error&&total>0?<div className="search-groups"><SearchGroup title="Scripture" count={bible.length}>{bible.map((item)=><Link className="search-hit" key={item.verseKey} to={bibleSearchHref(item)}><span>{item.bookName} {item.chapter}:{item.verse}</span><p>{item.text}</p></Link>)}</SearchGroup><SearchGroup title="Prayers" count={personal.prayers.length}>{personal.prayers.map((item)=><PersonalHit key={`${item.kind}-${item.id}`} item={item}/>)}</SearchGroup><SearchGroup title="Reflections" count={personal.reflections.length}>{personal.reflections.map((item)=><PersonalHit key={item.id} item={item}/>)}</SearchGroup><SearchGroup title="People" count={personal.people.length}>{personal.people.map((item)=><PersonalHit key={item.id} item={item}/>)}</SearchGroup><SearchGroup title="Saved Scripture" count={personal.saved.length}>{personal.saved.map((item)=><PersonalHit key={`${item.kind}-${item.id}`} item={item} manifest={manifest}/>)}</SearchGroup></div>:null}</main>;
}

function SearchGroup({title,count,children}:{title:string;count:number;children:ReactNode}){if(!count)return null;return <section className="search-group"><div className="section-heading-line compact"><h2>{title}</h2><span className="quiet-count">{count}{count===(title==="Scripture"?30:12)?" shown":""}</span></div>{count?<div className="search-hit-list">{children}</div>:<p className="muted-copy">No matches in {title.toLowerCase()}.</p>}</section>;}
function PersonalHit({item,manifest=null}:{item:PersonalSearchHit;manifest?:BibleManifest|null}){return <Link className="search-hit" to={item.href}><span>{item.kind}</span><strong>{item.reference?prayerReferenceLabel(item.reference,manifest):item.title}</strong>{item.excerpt&&item.excerpt!==item.title?<p>{item.excerpt}</p>:null}</Link>;}
