import { expect,test } from '@playwright/test';
import { seedHistoryJournal } from '../ux/history-fixture';
import { openRoute } from '../ux/helpers';

for(const state of ['empty-period','empty-segment','all-time','day-unavailable','day-prayed','quote-unavailable'])test(`History journal ${state}`,async({page})=>{
  await page.setViewportSize({width:390,height:844});await seedHistoryJournal(page,{priorYear:true});
  if(state==='empty-period'){await openRoute(page,'/history?period=2024');await expect(page.getByText('A quiet chapter.',{exact:true})).toBeVisible();}
  if(state==='empty-segment'){await openRoute(page,'/history?period=2025&view=reflections');await expect(page.getByText('No entries in this view.',{exact:true})).toBeVisible();}
  if(state==='all-time'){await page.getByLabel('History period').selectOption('all');await expect(page.getByRole('heading',{name:'A Record of Grace'})).toBeVisible();}
  if(state==='day-unavailable'||state==='day-prayed'){
    await page.evaluate(async state=>{const database=await new Promise<IDBDatabase>(resolve=>{const request=indexedDB.open('my-daily-devotion');request.onsuccess=()=>resolve(request.result);});const tx=database.transaction(['reflections','activityEvents'],'readwrite');const done=new Promise<void>(resolve=>{tx.oncomplete=()=>resolve();});if(state==='day-unavailable'){const request=tx.objectStore('reflections').get('history-reflection');request.onsuccess=()=>tx.objectStore('reflections').put({...request.result,deletedAt:'2026-04-24T06:00:00.000Z'});}else for(let i=0;i<3;i++)tx.objectStore('activityEvents').put({id:`prayed-${i}`,type:'PRAYER_PRAYED',localDate:'2026-04-24',occurredAt:`2026-04-24T07:0${i}:00.000Z`,subjectType:'prayer',subjectId:'history-prayer-0',metadata:{},timeZone:'Europe/Berlin'});await done;database.close();},state);
    await openRoute(page,state==='day-prayed'?'/history/day/2026-04-24?entry=prayed-2':'/history/day/2026-04-22?entry=history-reflection-event');await expect(page.locator('.history-day-entry.is-selected')).toBeFocused();if(state==='day-unavailable'){await expect(page.getByRole('heading',{name:'Reflection written',exact:true})).toBeVisible();await expect(page.locator('.history-entry-text')).toHaveCount(0);}
  }
  if(state==='quote-unavailable'){await page.route('**/bible/books/LAM.json',route=>route.abort());await page.reload();await expect(page.locator('.history-reflection-band > p')).toBeVisible();}
  await page.evaluate(()=>document.fonts.ready);await page.mouse.move(0,0);await expect(page).toHaveScreenshot(`history-${state}.png`);
});
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date('2026-04-24T07:00:00+02:00'));});
for(const [width,height] of [[320,568],[360,800],[390,844],[430,932],[768,1024],[1440,900]])test(`History journal light ${width}`,async({page})=>{await page.setViewportSize({width,height});await seedHistoryJournal(page);await page.mouse.move(0,0);await expect(page).toHaveScreenshot(`history-light-${width}.png`);});
for(const screen of ['calendar','day','moments'])for(const width of [320,360,430,768,1440])test(`History ${screen} ${width}`,async({page})=>{await page.setViewportSize({width,height:900});await seedHistoryJournal(page);if(screen==='day')await page.locator('#history-row-history-reflection-event').click();else await page.getByRole('link',{name:screen==='calendar'?'Browse dates':'Moments',exact:true}).click();await expect(page.locator('.grace-history')).toBeVisible();await expect(page).toHaveURL(new RegExp(`/history/${screen}`));await expect(page.getByRole('heading',{level:1})).toContainText(screen==='calendar'?'Browse dates':screen==='moments'?'Moments':'April');await expect(page.getByRole('status').filter({hasText:/Opening/})).toHaveCount(0);if(screen==='day')await expect(page.locator('.history-day-entry.is-selected')).toBeFocused();await page.evaluate(()=>document.fonts.ready);await page.mouse.move(0,0);await expect(page).toHaveScreenshot(`history-${screen}-${width}.png`);});
for(const screen of ['calendar','day','moments'])for(const mode of ['dark','enlarged'])test(`History ${screen} ${mode}`,async({page})=>{await page.setViewportSize({width:mode==='enlarged'?320:390,height:844});if(mode==='dark')await page.emulateMedia({colorScheme:'dark'});await seedHistoryJournal(page);if(screen==='day')await page.locator('#history-row-history-reflection-event').click();else await page.getByRole('link',{name:screen==='calendar'?'Browse dates':'Moments',exact:true}).click();await expect(page).toHaveURL(new RegExp(`/history/${screen}`));await expect(page.getByRole('heading',{level:1})).toContainText(screen==='calendar'?'Browse dates':screen==='moments'?'Moments':'April');await expect(page.getByRole('status').filter({hasText:/Opening/})).toHaveCount(0);if(screen==='day')await expect(page.locator('.history-day-entry.is-selected')).toBeFocused();if(mode==='enlarged')await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});await page.evaluate(()=>document.fonts.ready);await page.mouse.move(0,0);await expect(page).toHaveScreenshot(`history-${screen}-${mode}.png`,{fullPage:mode==='enlarged'});});
for(const state of ['dark','empty','long','year','enlarged','calendar','calendar-narrow','day','day-expanded','moments','error'])test(`History journal ${state}`,async({page})=>{
  await page.setViewportSize({width:state==='enlarged'||state==='calendar-narrow'?320:390,height:844});
  if(state==='dark')await page.emulateMedia({colorScheme:'dark'});
  if(state==='enlarged')await page.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{document.documentElement.style.fontSize='200%';}));
  if(state==='empty'){await openRoute(page,'/history');await expect(page.locator('.history-journal-empty')).toBeVisible();await expect(page.locator('.history-reflection-band blockquote')).toBeVisible();}else await seedHistoryJournal(page,{long:state==='long'||state==='day-expanded',priorYear:state==='year'});
  if(state==='year')await page.getByLabel('History period').selectOption('2025');
  if(state.startsWith('calendar')){await page.getByRole('link',{name:'Browse dates',exact:true}).click();await expect(page.getByRole('heading',{name:'April 2026'})).toBeVisible();}
  if(state.startsWith('day')){await page.locator('#history-row-history-reflection-event').click();await expect(page.locator('.history-day-entry.is-selected')).toBeFocused();}
  if(state==='moments'){await page.getByRole('link',{name:'Moments',exact:true}).click();await expect(page.locator('.history-journal-row')).toHaveCount(2);}
  if(state==='error'){await page.addInitScript(()=>{const original=IDBObjectStore.prototype.getAll;IDBObjectStore.prototype.getAll=function(...args){if(this.name==='activityEvents')throw new DOMException('Test read failure','UnknownError');return original.apply(this,args);};});await page.reload();await expect(page.getByRole('alert')).toBeVisible();await expect(page.locator('.history-reflection-band blockquote')).toBeVisible();}
  await page.evaluate(()=>document.fonts.ready);await page.mouse.move(0,0);await expect(page).toHaveScreenshot(`history-${state}.png`,{fullPage:state==='enlarged'||state==='day-expanded'});
});
