import {expect,test} from "@playwright/test";
import {seedFocusedPrayer} from "../ux/focused-prayer-fixture";
import {expectNoHorizontalOverflow,expectNoAxeViolations} from "../ux/helpers";
async function settle(page:import("@playwright/test").Page){await page.evaluate(async()=>{await document.fonts.ready;await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));window.scrollTo({top:0,behavior:"instant"});});await page.mouse.move(0,0);}
test.beforeEach(async({page})=>{await page.clock.setFixedTime(new Date("2026-04-24T07:00:00+02:00"));});
for(const [width,height] of [[320,568],[360,800],[390,844],[430,932],[768,1024],[1440,900]])test(`Session answer recovery ${width}`,async({page})=>{
 await page.setViewportSize({width,height});await seedFocusedPrayer(page);await page.getByRole("button",{name:"Mark answered",exact:true}).click();await page.locator("#session-answer-note").fill("Provision and peace in the season ahead.");await expect(page.locator(".draft-status")).toHaveText("Draft kept on this device");await page.reload();await page.getByRole("button",{name:"Mark answered",exact:true}).click();await page.getByText("Kept drafts for this editor",{exact:true}).click();await expectNoHorizontalOverflow(page);await settle(page);await expect(page).toHaveScreenshot(`session-answer-recovery-${width}.png`,{fullPage:true});
});
for(const state of ["dark","text200","review","kept","failure","long","discard","midnight"])test("Session answer recovery "+state,async({page})=>{
 await page.setViewportSize({width:state==="text200"?320:390,height:844});if(state==="dark")await page.emulateMedia({colorScheme:"dark"});await seedFocusedPrayer(page);await page.getByRole("button",{name:"Mark answered",exact:true}).click();
 if(state==="failure")await page.evaluate(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==="editorDraftContents")throw new DOMException("Draft storage unavailable","QuotaExceededError");return put.apply(this,args);};});
 await page.locator("#session-answer-note").fill(state==="long"?("Provision and peace in the season ahead.\n\n").repeat(24):"Provision and peace in the season ahead.");if(state==="failure")await expect(page.getByRole("alert")).toContainText("Draft could not be kept");else await expect(page.locator(".draft-status")).toHaveText("Draft kept on this device");
 if(state==="text200")await page.evaluate(()=>{document.documentElement.style.fontSize="200%";});if(state==="midnight")await page.clock.setFixedTime(new Date("2026-04-25T07:00:00+02:00"));if(state==="discard"){await page.locator(".session-answer").getByRole("button",{name:"Cancel editing",exact:true}).click();await expect(page.getByRole("dialog")).toBeVisible();}if(state==="review"){await page.reload();await page.getByRole("button",{name:"Mark answered",exact:true}).click();await page.getByText("Kept drafts for this editor",{exact:true}).click();await page.getByRole("button",{name:/Review kept draft/}).click();}
 await expectNoHorizontalOverflow(page);await expectNoAxeViolations(page);await settle(page);await expect(page).toHaveScreenshot(`session-answer-recovery-${state}.png`,{fullPage:state!=="discard"&&state!=="review"});
});
