import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const root = new URL("../", import.meta.url); const read = (path) => readFile(new URL(path, root), "utf8");
const [contractRaw, schema, types, schedules, queue, sessions, metadata, prayers, admin, prayerScreen, sessionScreen, detail, app, main, pkgRaw] = await Promise.all([
  read("canonical/domain-contract.v1.json"), read("src/data/schema.ts"), read("src/domain/types.ts"), read("src/prayer/scheduling.ts"), read("src/prayer/queue.ts"), read("src/data/repositories/prayer-sessions.ts"), read("src/data/repositories/prayer-metadata.ts"), read("src/data/repositories/prayers.ts"), read("src/prayer/PrayerAdministrationFields.tsx"), read("src/prayer/PrayerScreen.tsx"), read("src/prayer/PrayerSessionScreen.tsx"), read("src/prayer/PrayerDetailScreen.tsx"), read("src/app/App.tsx"), read("src/main.tsx"), read("package.json"),
]);
const contract = JSON.parse(contractRaw); const pkg = JSON.parse(pkgRaw);
assert.equal(contract.prayer.missedRecurrenceCreatesDebt, false); assert.deepEqual(contract.prayer.queue.precedence, ["FOCUS_OR_EVENT", "FIXED_DUE", "NEVER_PRAYED", "ROTATION"]); assert.match(schema, /DATABASE_SCHEMA_VERSION = 1/); for (const store of ["prayerSchedules", "prayerSessions", "prayerSessionItems", "people", "categories"]) assert.match(schema, new RegExp(`${store}:`)); assert.doesNotMatch(types, /priority\s*:/i);
for (const mode of ["ROTATION", "DAILY", "WEEKDAYS", "INTERVAL_DAYS", "MONTHLY", "ON_DATE", "MANUAL_ONLY"]) assert.match(schedules, new RegExp(mode)); assert.match(schedules, /event-follow-up/); assert.match(schedules, /localDate/);
for (const band of ["FOCUS_OR_EVENT", "FIXED_DUE", "NEVER_PRAYED", "ROTATION"]) assert.match(queue, new RegExp(band)); assert.match(queue, /MANUAL_ONLY/); assert.match(queue, /prayedOnDate/); assert.match(queue, /seen\.has/);
assert.match(sessions, /startOrResume/); assert.match(sessions, /PrayerSessionItem/); assert.match(sessions, /outcome: "NEXT"/); assert.match(sessions, /outcome: "SKIP"/); assert.match(sessions, /endSession/); assert.match(sessions, /localDate/);
assert.match(metadata, /PersonRepository/); assert.match(metadata, /CategoryRepository/); assert.match(metadata, /Personal/); assert.match(metadata, /Mission/); assert.match(prayers, /updateAdministration/); assert.match(prayers, /PrayerScheduleDraft/);
assert.match(admin, /Normal rotation/); assert.match(admin, /Selected weekdays/); assert.match(admin, /Every N days/); assert.match(admin, /Manual only/); assert.match(admin, /Focus until/); assert.match(admin, /Event date/);
assert.match(prayerScreen, /Resume session/); assert.match(prayerScreen, /People/); assert.match(prayerScreen, /Categories/); assert.match(sessionScreen, /Exit & resume later/); assert.match(sessionScreen, /End session/); assert.match(sessionScreen, /sessions\.next/); assert.match(sessionScreen, /sessions\.skip/); assert.match(detail, /Prayer details/); assert.match(detail, /scheduleLabel/);
for (const route of ["/prayer/people", "/prayer/categories", "/prayer/session", "/prayer/:prayerId/settings"]) assert.ok(app.includes(route), `Missing ${route}`); assert.ok(main.includes("phase7.css")); assert.ok(pkg.scripts["verify:phase7"]); const [major, minor] = pkg.version.split(".").map(Number); assert.ok(major > 0 || minor >= 7, `Expected app version >= 0.7.0, got ${pkg.version}`);
console.log("✓ Phase 7 Prayer Scheduling, Queue & Focused Session verification passed"); console.log("  seven schedule modes + timezone-safe recurrence with no missed-day debt"); console.log("  deterministic four-band queue + People/categories + event/Focus metadata certified"); console.log("  durable resumable PrayerSession/PrayerSessionItem semantics wired to UI");
