import {afterEach,expect,it,vi} from "vitest";
import {MddDatabase,prepareDatabase} from "../data/database";
import {DurableDraftController} from "./controller";
import {DraftRepository} from "./repository";
import {saveDirectoryDraft,rebaseDirectoryDraft} from "./directory-adapters";
import {PersonRepository,CategoryRepository} from "../data/repositories/prayer-metadata";
import {CollectionRepository} from "../data/repositories/collections";
import {reflectionRecoveryDestination} from "./presentation";
import type {DraftPayload} from "./types";
const databases:MddDatabase[]=[],controllers:DurableDraftController[]=[];
async function setup(){const database=new MddDatabase("directory-draft-"+crypto.randomUUID());databases.push(database);await prepareDatabase(database);const controller=new DurableDraftController(database,{returnTo:"/prayer/people?q=Anna&shown=40&return=%2Fhistory",reading:null});controllers.push(controller);return {database,controller,repository:new DraftRepository(database)};}
afterEach(async()=>{vi.restoreAllMocks();for(const c of controllers.splice(0))c.detach();for(const db of databases.splice(0)){db.close();await db.delete();}});
const create:DraftPayload={kind:"person-create",name:"Anna",relationship:"Friend",notes:"Private writing"};
it("keeps input arriving during creation ownership transfer as a newer editable generation",async()=>{
 const {database,controller,repository}=await setup();controller.stage(create);
 const saved=await controller.commit(async context=>{const result=await saveDirectoryDraft(database,context);controller.stage({...create,notes:'First newer notes'});return result;});
 const persist=DraftRepository.prototype.persist;
 vi.spyOn(DraftRepository.prototype,'persist').mockImplementationOnce(function(this:DraftRepository,snapshot,expected){controller.stage({...create,notes:'Even newer notes'});return persist.call(this,snapshot,expected);});
 const adopted=await controller.adoptCreatedRecord(payload=>rebaseDirectoryDraft(payload,saved.record!));expect(adopted).toMatchObject({kind:'person-edit',notes:'Even newer notes'});await controller.flush();
 expect(await repository.read(controller.getId()!)).toMatchObject({kind:'active',snapshot:{contents:{payload:{kind:'person-edit',notes:'Even newer notes'}},metadata:{generation:2}}});expect(await database.people.count()).toBe(1);expect(await database.activityEvents.count()).toBe(0);
});
it("keeps incomplete metadata without creating records and retires only its saved generation",async()=>{const {database,controller,repository}=await setup();controller.stage({...create,name:""});await controller.flush();expect(await database.people.count()).toBe(0);expect(await database.activityEvents.count()).toBe(0);controller.stage(create);const result=await controller.commit(c=>saveDirectoryDraft(database,c));expect(result.record).toMatchObject({name:"Anna",revision:1});expect((await repository.read(controller.getId()!)).kind).toBe("committed");expect(await database.people.count()).toBe(1);expect(await database.activityEvents.count()).toBe(0);});
it("moves newer creation text to an editable owner without duplicate people",async()=>{const {database,controller,repository}=await setup();controller.stage(create);const original=saveDirectoryDraft;const result=await controller.commit(async c=>{const saved=await original(database,c);controller.stage({...create,notes:"Newer private writing"});return saved;});const old=controller.getId()!;expect((await repository.read(old)).kind).toBe("active");const payload=await controller.adoptCreatedRecord(p=>rebaseDirectoryDraft(p,result.record!));expect(payload).toMatchObject({kind:"person-edit",notes:"Newer private writing",baseline:{id:result.record!.id,revision:1}});expect(controller.getId()).not.toBe(old);expect((await repository.read(old)).kind).toBe("discarded");const saved=await controller.commit(c=>saveDirectoryDraft(database,c),(latest,_submitted,result)=>rebaseDirectoryDraft(latest,(result as Awaited<ReturnType<typeof saveDirectoryDraft>>).record!));expect(saved.record).toMatchObject({notes:"Newer private writing",revision:2});expect(await database.people.count()).toBe(1);expect(await database.activityEvents.count()).toBe(0);});
it("rolls back a failed private ownership transfer and preserves copyable writing",async()=>{const {database,controller,repository}=await setup();controller.stage(create);const saved=await controller.commit(async c=>{const result=await saveDirectoryDraft(database,c);controller.stage({...create,notes:"Never lose this"});return result;});const id=controller.getId()!;vi.spyOn(DraftRepository.prototype,"persist").mockRejectedValueOnce(new Error("Storage unavailable"));await expect(controller.adoptCreatedRecord(p=>rebaseDirectoryDraft(p,saved.record!))).rejects.toThrow("Storage unavailable");expect(await database.people.count()).toBe(1);expect(await repository.read(id)).toMatchObject({kind:"active",snapshot:{contents:{payload:{notes:"Never lose this"}}}});await expect(controller.commit(c=>saveDirectoryDraft(database,c))).rejects.toThrow("already recorded");});
it("category deduplication stays truthful and has no history side effects",async()=>{const {database,controller}=await setup();const original=await new CategoryRepository(database).createCategory("Family");controller.stage({kind:"category-create",name:" family "});const saved=await controller.commit(c=>saveDirectoryDraft(database,c));expect(saved.created).toBe(false);expect(saved.record?.id).toBe(original.id);expect(await database.categories.count()).toBe(1);expect(await database.activityEvents.count()).toBe(0);});
it("unchanged normalized metadata retires its draft without a domain revision",async()=>{const {database,controller}=await setup();const person=await new PersonRepository(database).createPerson("Anna","Friend","Notes");controller.stage({kind:"person-edit",name:" Anna ",relationship:" Friend ",notes:" Notes ",baseline:{id:person.id,revision:person.revision,name:person.name,relationship:person.relationship,notes:person.notes}});const saved=await controller.commit(c=>saveDirectoryDraft(database,c));expect(saved.record).toEqual(person);expect(await database.people.get(person.id)).toEqual(person);expect(await database.activityEvents.count()).toBe(0);});
it("stale or deleted metadata cannot be recreated by recovery saves",async()=>{const {database,controller,repository}=await setup();const person=await new PersonRepository(database).createPerson("Anna");controller.stage({kind:"person-edit",name:"Changed",relationship:"",notes:"Keep",baseline:{id:person.id,revision:person.revision,name:person.name,relationship:person.relationship,notes:person.notes}});await controller.flush();await new PersonRepository(database).removePerson(person.id,1);await expect(controller.commit(c=>saveDirectoryDraft(database,c))).rejects.toThrow("changed or was removed");expect(await repository.read(controller.getId()!)).toMatchObject({kind:"active"});expect(await reflectionRecoveryDestination(database,await repository.read(controller.getId()!))).toBeNull();});
it("collection names and notes preserve descriptions, relationships and readonly recovery context",async()=>{const {database,controller,repository}=await setup();const collections=new CollectionRepository(database);const parent=await collections.create("Promises","Saved description"),item=await collections.addReference(parent.id,{translationId:"BSB",startVerseKey:"JHN.3.35",endVerseKey:"JHN.4.3"},"First note");controller.setContext({returnTo:"/bible/collections?collection="+parent.id+"&item="+item.id+"&shown=40&return=%2Fsearch",reading:null});controller.stage({kind:"collection-item-note",note:"New note",collection:{id:parent.id,revision:parent.revision},baseline:{id:item.id,revision:item.revision,note:item.note}});await controller.flush();const before=await Promise.all(database.tables.map(t=>t.toArray()));const destination=await reflectionRecoveryDestination(database,await repository.read(controller.getId()!));expect(destination).toContain("/bible/collections?");expect(new URLSearchParams(destination!.split("?")[1]).get("shown")).toBe("40");expect(await Promise.all(database.tables.map(t=>t.toArray()))).toEqual(before);const saved=await controller.commit(c=>saveDirectoryDraft(database,c));expect(saved.record).toMatchObject({note:"New note",endVerseKey:"JHN.4.3",revision:2});expect(await database.collections.get(parent.id)).toEqual(parent);expect(await database.activityEvents.count()).toBe(0);});
it("checks both the collection and child revision atomically",async()=>{const {database,controller,repository}=await setup();const collections=new CollectionRepository(database);const parent=await collections.create("Promises"),item=await collections.addReference(parent.id,{translationId:"BSB",startVerseKey:"JHN.3.16",endVerseKey:"JHN.3.18"});controller.stage({kind:"collection-item-note",note:"Private",collection:{id:parent.id,revision:1},baseline:{id:item.id,revision:1,note:null}});await controller.flush();await collections.rename(parent.id,"Changed",null,1);await expect(controller.commit(c=>saveDirectoryDraft(database,c))).rejects.toThrow("collection changed");expect(await database.collectionItems.get(item.id)).toEqual(item);expect(await repository.read(controller.getId()!)).toMatchObject({kind:"active"});});
