import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { useUnsavedChanges } from "../app/useUnsavedChanges";
import { Icon } from "../app/visual/Icon";
import { db } from "../data/database";
import { PRAYER_DEPTH_TARGETS, PrayerSessionRepository, type PrayerDepth, type PrayerSessionState } from "../data/repositories/prayer-sessions";
import { PrayerRepository } from "../data/repositories/prayers";
import { todayLocalDate } from "../domain/time";
import type { Person, PrayerUpdate, ScriptureLink } from "../domain/types";
import { loadBibleManifest } from "../scripture/loader";
import type { BibleManifest } from "../scripture/types";
import { prayerBibleHref, prayerReferenceLabel } from "./references";

const sessions = new PrayerSessionRepository(db); const prayers = new PrayerRepository(db);
export function PrayerSessionScreen() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const requested = params.get("depth") as PrayerDepth | null; const depth: PrayerDepth = requested && Object.hasOwn(PRAYER_DEPTH_TARGETS, requested) ? requested : "quick"; const [state, setState] = useState<PrayerSessionState | null>(null); const [updates, setUpdates] = useState<PrayerUpdate[]>([]); const [links, setLinks] = useState<ScriptureLink[]>([]); const [person, setPerson] = useState<Person | null>(null); const [manifest, setManifest] = useState<BibleManifest | null>(null); const [answerOpen, setAnswerOpen] = useState(false); const [answerBody, setAnswerBody] = useState(""); const [loading, setLoading] = useState(true); const [status, setStatus] = useState("");
  const allowNavigation = useUnsavedChanges(Boolean(answerBody));
  const [busy, setBusy] = useState(false);
  const acting = useRef(false);
  const refresh = useCallback(async (sessionId: string) => setState(await sessions.loadState(sessionId)), []);
  useEffect(() => { let cancelled = false; Promise.all([sessions.startOrResume(depth, todayLocalDate()), loadBibleManifest()]).then(([nextState, nextManifest]) => { if (!cancelled) { setState(nextState); setManifest(nextManifest); setLoading(false); } }).catch((reason: unknown) => { if (!cancelled) { setStatus(reason instanceof Error ? reason.message : "Could not start prayer session."); setLoading(false); } }); return () => { cancelled = true; }; }, [depth]);
  const currentEntry = state?.entries.find((entry) => entry.item.outcome === null && entry.prayer?.status === "ACTIVE") ?? null; const current = currentEntry?.prayer ?? null; const actedCount = state?.entries.filter((entry) => entry.item.outcome !== null).length ?? 0;
  useEffect(() => { let cancelled = false; if (!current) { setUpdates([]); setLinks([]); setPerson(null); return () => { cancelled = true; }; } Promise.all([prayers.listUpdates(current.id), prayers.listScriptureLinks(current.id), current.personId ? db.people.get(current.personId) : Promise.resolve(undefined)]).then(([nextUpdates, nextLinks, nextPerson]) => { if (!cancelled) { setUpdates(nextUpdates); setLinks(nextLinks); setPerson(nextPerson && !nextPerson.deletedAt ? nextPerson : null); setAnswerOpen(false); setAnswerBody(""); } }).catch(() => { if (!cancelled) setStatus("Could not open this request’s context. Your session is preserved; reopen it to try again."); }); return () => { cancelled = true; }; }, [current]);
  const latestUpdate = useMemo(() => updates.at(-1) ?? null, [updates]);
  const act = async (action: "next" | "skip") => { if (!state || !currentEntry || acting.current) return; if (answerBody && !window.confirm("Discard the unsaved answer note?")) return; acting.current = true; setBusy(true); try { if (action === "next") await sessions.next(state.session.id, currentEntry.item.id); else await sessions.skip(state.session.id, currentEntry.item.id); await refresh(state.session.id); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not update prayer session."); } finally { acting.current = false; setBusy(false); } };
  const answer = async () => { if (!state || !currentEntry || acting.current) return; acting.current = true; setBusy(true); try { await sessions.answer(state.session.id, currentEntry.item.id, answerBody); setAnswerBody(""); await refresh(state.session.id); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not mark prayer answered."); } finally { acting.current = false; setBusy(false); } };
  const end = async () => { if (!state || acting.current) return; if (answerBody && !window.confirm("Discard the unsaved answer note and end this session?")) return; acting.current = true; setBusy(true); try { await sessions.endSession(state.session.id); allowNavigation(); navigate("/prayer", { replace: true }); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Could not end this session. Try again."); } finally { acting.current = false; setBusy(false); } };
  if (loading) return <main className="visual-screen focused-prayer-screen"><p className="eyebrow">Focused prayer</p><p>Preparing a quiet session…</p></main>;
  if (status && !state) return <main className="visual-screen focused-prayer-screen"><p className="eyebrow">Focused prayer</p><h1>Session unavailable</h1><p role="alert">{status}</p><Link to="/prayer">Return to Prayer</Link></main>;
  if (!state) return <main className="visual-screen focused-prayer-screen"><p className="eyebrow">Focused prayer</p><h1>No prayers to surface</h1><p className="screen-intro">There are no active requests eligible for an automatic session today. Manual-only requests remain in your Prayer list.</p><Link className="future-text-link" to="/prayer">Return to Prayer →</Link></main>;
  if (!current) return <main className="visual-screen focused-prayer-screen"><p className="eyebrow">Focused prayer</p><h1>Session finished.</h1><p className="screen-intro">You can return whenever you are ready to pray again.</p><Link className="future-text-link" to="/prayer">Return to Prayer →</Link></main>;
  return <main className="visual-screen focused-prayer-screen mg-secondary-screen mg-focused-prayer-workspace"><header className="focused-prayer-header"><Link to="/prayer">Exit & resume later</Link><span>{actedCount + 1} / {state.entries.length}</span><button type="button" disabled={busy} className="end-session-button" onClick={() => void end()}>End session</button></header><article className="focused-prayer-card">{person ? <p className="focused-person">{person.name}{person.relationship ? ` · ${person.relationship}` : ""}</p> : <p className="section-kicker">Prayer</p>}<h1>{current.body}</h1>{latestUpdate ? <div className={latestUpdate.type === "encouragement" ? "focused-latest is-encouragement" : "focused-latest"}><span>Latest {latestUpdate.type}</span><p>{latestUpdate.body}</p></div> : null}{links.length ? <div className="focused-scripture">{links.map((link) => <Link key={link.id} to={prayerBibleHref(link)}>{prayerReferenceLabel(link, manifest)}</Link>)}</div> : null}{answerOpen ? <div className="focused-answer-form"><label htmlFor="focused-answer">What happened? <span>optional</span></label><textarea disabled={busy} id="focused-answer" value={answerBody} onChange={(event) => setAnswerBody(event.target.value)} /><div><button type="button" disabled={busy} onClick={() => void answer()}>Mark answered</button><button type="button" disabled={busy} onClick={() => { if (!answerBody || window.confirm("Discard the unsaved answer note?")) {setAnswerOpen(false);setAnswerBody("");} }}>Cancel</button></div></div> : null}<div className="focused-prayer-secondary"><Link to={`/prayer/${current.id}`}>Update / details</Link><button type="button" disabled={busy} onClick={() => setAnswerOpen(true)}>Answered</button><button type="button" disabled={busy} onClick={() => void act("skip")}>Skip</button></div><button disabled={busy} className="focused-next-button" type="button" onClick={() => void act("next")}>Prayed · Next <Icon name="arrow" /></button><p className="reader-status" aria-live="polite">{status}</p></article></main>;
}
