import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Icon } from "../app/visual/Icon";
import { db } from "../data/database";
import { PrayerSessionRepository } from "../data/repositories/prayer-sessions";
import { PrayerRepository } from "../data/repositories/prayers";
import { todayLocalDate } from "../domain/time";
import type { Prayer, PrayerSession, PrayerStatus } from "../domain/types";

const repository = new PrayerRepository(db); const sessions = new PrayerSessionRepository(db);
const statuses: PrayerStatus[] = ["ACTIVE", "WAITING", "ANSWERED", "ARCHIVED"];
const labels: Record<PrayerStatus, string> = { ACTIVE: "Active", WAITING: "Waiting", ANSWERED: "Answered", ARCHIVED: "Archived" };
function lastPrayedLabel(prayer: Prayer): string { if (!prayer.lastPrayedAt) return "Not prayed in MDD yet"; return `Last prayed ${new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(prayer.lastPrayedAt))}`; }

export function PrayerScreen() {
  const [params] = useSearchParams(); const requested = params.get("status")?.toUpperCase() as PrayerStatus | undefined; const selected: PrayerStatus = requested && statuses.includes(requested) ? requested : "ACTIVE"; const [items, setItems] = useState<Prayer[]>([]); const [all, setAll] = useState<Prayer[]>([]); const [openSession, setOpenSession] = useState<PrayerSession | null>(null); const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => { setLoading(true); const [nextItems, nextAll, session] = await Promise.all([repository.listByStatus(selected), repository.listActive(), sessions.getOpenSession()]); setItems(nextItems); setAll(nextAll); setOpenSession(session?.localDate === todayLocalDate() ? session : null); setLoading(false); }, [selected]); useEffect(() => { void refresh(); }, [refresh]);
  const counts = useMemo(() => Object.fromEntries(statuses.map((status) => [status, all.filter((item) => item.status === status).length])) as Record<PrayerStatus, number>, [all]);
  return <main className="visual-screen prayer-screen live-prayer-screen"><header className="screen-heading compact-heading prayer-main-heading"><p className="eyebrow">Prayer</p><h1>Prayer</h1><p className="screen-intro">Focus and due requests surface first, then new and least-recently-prayed requests. Scheduling supports prayer without creating an inbox of overdue debt.</p><div className="prayer-primary-actions"><Link className="primary-editorial-action compact-action" to="/prayer/new">Add prayer <Icon name="arrow" /></Link>{openSession ? <Link className="prayer-now-link" to={`/prayer/session?depth=${openSession.depth}`}>Resume session</Link> : counts.ACTIVE > 0 ? <Link className="prayer-now-link" to="/prayer/session?depth=quick">Pray now</Link> : null}</div><div className="prayer-management-links"><Link to="/prayer/people">People</Link><Link to="/prayer/categories">Categories</Link></div></header>
  {counts.ACTIVE > 0 ? <section className="prayer-session-choices" aria-label="Focused prayer depth"><p className="section-kicker">Focused prayer</p>{openSession ? <p className="session-resume-note">An unfinished {openSession.depth} session from today is preserved. Any depth link resumes that same frozen queue.</p> : null}<div><Link to="/prayer/session?depth=quick"><strong>Quick</strong><span>target 4 requests</span></Link><Link to="/prayer/session?depth=regular"><strong>Regular</strong><span>target 10 requests</span></Link><Link to="/prayer/session?depth=extended"><strong>Extended</strong><span>target 20 requests</span></Link></div><small className="session-depth-note">Focus, event, and fixed-due requests are not dropped merely to fit a target.</small></section> : null}
  <nav className="prayer-status-tabs" aria-label="Prayer status">{statuses.map((status) => <Link key={status} className={selected === status ? "is-active" : ""} to={`/prayer?status=${status}`}><span>{labels[status]}</span><small>{counts[status]}</small></Link>)}</nav><section className="prayer-live-list" aria-live="polite">{loading ? <p className="muted-copy">Opening prayers…</p> : items.length === 0 ? <div className="prayer-empty"><h2>No {labels[selected].toLowerCase()} prayers.</h2><p>{selected === "ACTIVE" ? "Add a request when there is something you genuinely want to carry into prayer." : "Nothing needs to be here."}</p>{selected === "ACTIVE" ? <Link to="/prayer/new">Add prayer →</Link> : null}</div> : items.map((prayer) => <Link className="prayer-live-row" to={`/prayer/${prayer.id}`} key={prayer.id}><div><span className={`prayer-status-word status-${prayer.status.toLowerCase()}`}>{labels[prayer.status]}</span><p>{prayer.body}</p><small>{lastPrayedLabel(prayer)}</small></div><Icon name="arrow" /></Link>)}</section></main>;
}
