import { useEffect, useRef, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { useUnsavedChanges } from "../app/useUnsavedChanges";
import { ConflictReview } from "../app/ConflictReview";
import { isEditConflict } from "../data/conflicts";
import { db } from "../data/database";
import { CategoryRepository, PersonRepository } from "../data/repositories/prayer-metadata";
import { PrayerRepository } from "../data/repositories/prayers";
import type { Category, Person, Prayer } from "../domain/types";
import { administrationInputFromValue, administrationValueFrom, PrayerAdministrationFields, type PrayerAdministrationValue } from "./PrayerAdministrationFields";

const prayers = new PrayerRepository(db); const peopleRepository = new PersonRepository(db); const categoriesRepository = new CategoryRepository(db);
export function PrayerSettingsScreen() {
  const { prayerId = "" } = useParams(); const navigate = useNavigate(); const location = useLocation(); const detailTarget = `/prayer/${prayerId}${location.search}`; const [prayer, setPrayer] = useState<Prayer | null>(null); const [people, setPeople] = useState<Person[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [value, setValue] = useState<PrayerAdministrationValue | null>(null); const [status, setStatus] = useState("");
  const [conflict,setConflict] = useState(false); const [busy,setBusy] = useState(false);
  const [loading, setLoading] = useState(true); const baseline = useRef(""); const saving = useRef(false);
  const allowNavigation = useUnsavedChanges(Boolean(value && baseline.current && JSON.stringify(value) !== baseline.current));
  useEffect(() => { let cancelled = false; Promise.all([prayers.get(prayerId), prayers.getScheduleForPrayer(prayerId), peopleRepository.list(), categoriesRepository.list()]).then(([item, schedule, nextPeople, nextCategories]) => { if (!cancelled) { setPrayer(item ?? null); setPeople(nextPeople); setCategories(nextCategories); if (item) { const next = administrationValueFrom(item, schedule); baseline.current = JSON.stringify(next); setValue(next); } } }).catch(() => { if (!cancelled) setStatus("Could not open prayer details. Please try again."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [prayerId]);
  if (!loading && (!prayer || !value)) return <main className="visual-screen mg-secondary-screen mg-prayer-settings-workspace mg-route-state mg-error-state"><h1>Prayer unavailable</h1><p className="mg-inline-state">{status || "This prayer may have been removed."}</p><Link className="quiet-back-link" to="/prayer">Return to Prayer</Link></main>;
  if (!prayer || !value) return <main className="visual-screen mg-secondary-screen mg-prayer-settings-workspace mg-route-state mg-loading-state"><p className="eyebrow">Prayer details</p><p className="mg-inline-state">Opening prayer details…</p></main>;
  const save = async () => { if (saving.current) return; saving.current = true; setBusy(true); try { await prayers.updateAdministration(prayer.id, administrationInputFromValue(value), prayer.revision); allowNavigation(); navigate(detailTarget, { replace: true }); } catch (reason) { setConflict(isEditConflict(reason)); setStatus(reason instanceof Error ? reason.message : "Could not save prayer details."); } finally { saving.current = false; setBusy(false); } };
  return <main className="visual-screen prayer-settings-screen mg-secondary-screen mg-prayer-settings-workspace"><header className="screen-heading compact-heading mg-secondary-header"><p className="eyebrow">Prayer</p><h1>Prayer details</h1><p className="screen-intro">Choose when this prayer appears and who it is for.</p><Link className="quiet-back-link" to={detailTarget}>← Back to prayer</Link></header><section className="prayer-settings-panel"><fieldset disabled={busy} className="editor-fieldset"><PrayerAdministrationFields value={value} people={people} categories={categories} onChange={setValue} /></fieldset><div className="metadata-manage-links"><Link to="/prayer/people">Manage people</Link><Link to="/prayer/categories">Manage categories</Link></div><div className="prayer-settings-actions"><button className="primary-editorial-action compact-action" type="button" disabled={busy} onClick={() => void save()}>Save details</button><Link to={detailTarget}>Cancel</Link></div><p className="prayer-form-status" aria-live="polite">{status}</p><ConflictReview active={conflict} draftText={JSON.stringify(value,null,2)}
        loadLatest={async()=>{const item=await prayers.get(prayer.id);if(!item)throw new Error("This prayer is no longer available.");const schedule=await prayers.getScheduleForPrayer(item.id);return {item, value:administrationValueFrom(item,schedule)};}}
        describe={(latest)=>JSON.stringify(latest.value,null,2)} useLatest={(latest)=>{setPrayer(latest.item);setValue(latest.value);baseline.current=JSON.stringify(latest.value);setConflict(false);setStatus("Saved version loaded. You can now make your changes again.");}} /></section></main>;
}
